config/routes.rb
Rails.application.routes.draw do
  resources :kechengs

  get 'home/index'

  root 'home#index'

end

app/models/kecheng.rb
class Kecheng < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/kechengs_controller.rb
class KechengsController < ApplicationController
  before_action :set_kecheng, only: [:show, :edit, :update, :destroy]

  # GET /kechengs
  # GET /kechengs.json
  def index
    @kechengs = Kecheng.all
    if params[:name].present?
    @kecheng = Kecheng.where("name like ?","%#{params[:name]}%")
    end
    if params[:teacher].present?
    @kecheng = Kecheng.where("teacher like ?","%#{params[:teacher]}%")
    end
    if params[:time].present?
    @kecheng = Kecheng.where("time like ?","%#{params[:time]}%")
    end
  end

  # GET /kechengs/1
  # GET /kechengs/1.json
  def show
  end

  # GET /kechengs/new
  def new
    @kecheng = Kecheng.new
  end

  # GET /kechengs/1/edit
  def edit
  end

  # POST /kechengs
  # POST /kechengs.json
  def create
    @kecheng = Kecheng.new(kecheng_params)

    respond_to do |format|
      if @kecheng.save
        format.html { redirect_to @kecheng, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @kecheng }
      else
        format.html { render :new }
        format.json { render json: @kecheng.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kechengs/1
  # PATCH/PUT /kechengs/1.json
  def update
    respond_to do |format|
      if @kecheng.update(kecheng_params)
        format.html { redirect_to @kecheng, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @kecheng }
      else
        format.html { render :edit }
        format.json { render json: @kecheng.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kechengs/1
  # DELETE /kechengs/1.json
  def destroy
    @kecheng.destroy
    respond_to do |format|
      format.html { redirect_to kechengs_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kecheng
      @kecheng = Kecheng.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kecheng_params
      params.require(:kecheng).permit(:name, :teacher, :time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/kechengs_helper.rb
module KechengsHelper
end

app/views/home/index.html.erb
<h1>Coursequery System</h1>
<%= link_to "Courses List", kechengs_path %>

app/views/kechengs/_form.html.erb
<%= form_for(@kecheng) do |f| %>
  <% if @kecheng.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kecheng.errors.count, "error") %> prohibited this kecheng from being saved:</h2>

      <ul>
      <% @kecheng.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :teacher %><br>
    <%= f.text_field :teacher %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.text_field :time %>
  </div>
  <div class="actions">
    <%= f.submit "Create Course"%>
  </div>
<% end %>

app/views/kechengs/edit.html.erb
<h1>Editing Kecheng</h1>

<%= render 'form' %>

<%= link_to 'Show', @kecheng %> |
<%= link_to 'Back', kechengs_path %>

app/views/kechengs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses List</h1>

<%= form_tag kechengs_path,method:"get" do %>
<div>
課程名稱:<%= text_field_tag :name %>
老師名稱:<%= text_field_tag :teacher %>
時間:<%= text_field_tag :time %>
</div>
<%= submit_tag "search" %>
<%end%>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Teacher</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kechengs.each do |kecheng| %>
      <tr>
        <td><%= kecheng.name %></td>
        <td><%= kecheng.teacher %></td>
        <td><%= kecheng.time %></td>
        <td><%= link_to 'Show', kecheng %></td>
        <td><%= link_to 'Edit', edit_kecheng_path(kecheng) %></td>
        <td><%= link_to 'Destroy', kecheng, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_kecheng_path %>

app/views/kechengs/new.html.erb
<h1>New Course</h1>

<%= render 'form' %>

<%= link_to 'Back', kechengs_path %>

app/views/kechengs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @kecheng.name %>
</p>

<p>
  <strong>Teacher:</strong>
  <%= @kecheng.teacher %>
</p>

<p>
  <strong>Time:</strong>
  <%= @kecheng.time %>
</p>

<%= link_to 'Edit', edit_kecheng_path(@kecheng) %> |
<%= link_to 'Back', kechengs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Course</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body style="background: #EEEEEE;">
<%= yield %>

</body>
</html>